class PipelineException(Exception):
    """A base exception for all exceptions generated by a pipeline."""
    def __init__(self, msg: str):
        self.msg = msg


class StopPayloadException(PipelineException):
    """An exception that will stop the execution of a payload and ignore remaining steps then move on to the next payload without considering the payload errored."""


class StopPipelineException(PipelineException):
    """An exception that will stop the execution of a payload and all subsequent payloads, moving onto the post execution steps."""
